---
- name: Install and configure Nginx
  hosts: localhost
  become: true
  tasks:
     - include: tasks/docker.yml
     - include: tasks/snap.yml
     - include: tasks/google-chrome.yml
     - include: tasks/dev-tools.yml
     - include: tasks/docker-compose.yml
     - include: tasks/i3-gapps.yml
     - include: tasks/create_folder.yml
