---
    - name: Update package index
      become: yes
      apt:
        update_cache: yes

    - name: Install i3 Gaps dependencies
      become: yes
      tags:
        - i3-deps
      apt:
        name:
          - libxcb1-dev
          - libxcb-keysyms1-dev
          - libpango1.0-dev
          - libxcb-util0-dev
          - libxcb-icccm4-dev
          - libyajl-dev
          - libstartup-notification0-dev
          - libxcb-randr0-dev
          - libev-dev
          - libxcb-cursor-dev
          - libxcb-xinerama0-dev
          - libxcb-xkb-dev
          - libxkbcommon-dev
          - libxkbcommon-x11-dev
          - i3
          - thunar
          - thunderbird
          - jq
          - vim
          - rofi
          - xdotool
          - x11-xserver-utils
          - indent
          - libanyevent-i3-perl
        state: present